### ISSUE TITLE
Issue with Insertion Sort Algorith

### ISSUE THREAD

**Issue by acypert** [nimrod46/Data-Structures-and-Algorithms#2]
Hi - There's an issue with your insertion sort algorithm that arises if the same number arises in the array twice.

On line 23:

`if (list.get(i) > list.get(j - 1) && list.get(i) < list.get(j))`

needs to be changed to 

`if (list.get(i) >= list.get(j - 1) && list.get(i) < list.get(j))` and then it will sort correctly.

**Comment by nimrod46** [comment]
Thank you!! Fixed

**Comment by acypert** [comment]
You bet!
