### ISSUE TITLE
firstRecurringCharacter (Hash Tables) ~ 3rd Solution Does Not Work

### ISSUE THREAD

**Issue by BenzChua31** [nimrod46/Data-Structures-and-Algorithms#7]
The 3rd function does not work as the solution. This is because you are prepopulating the hash table with all the elements in the array. So when we check the hash table to see if it contains the element in the array, the if condition is always going to be True. 

The expected result for {1,5,8,5,1,8,8,7,4,4,10} should return 5 and not 1.

**Comment by nimrod46** [comment]
Why did you close this? Ur issue seems to be legit
